import './globals.css';
import Link from 'next/link';

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>
				<nav>
					<Link href="/">
						<span> Home </span>
					</Link>
					<Link href="/projects">
						<span> Projects </span>
					</Link>
					<Link href="/aboutme">
						<span> AboutMe </span>
					</Link>
					<Link href="/contact">
						<span> contact </span>
					</Link>
				</nav>
				{children}
			</body>
		</html>
	);
}
