import './globals.css';
import Link from 'next/link';
import Head from 'next/head';
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<body>
				<nav>
					<div className="menu">
						<Link href="/">
							<span> Home </span>
						</Link>
						<Link href="/projects">
							<span> Projects </span>
						</Link>
						<Link href="/aboutme">
							<span> AboutMe </span>
						</Link>
						<Link href="/contact">
							<span> contact </span>
						</Link>
					</div>
				</nav>

				{children}
			</body>
		</html>
	);
}
